name: audio_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  just_audio: ^0.9.32
  rxdart: ^0.27.7
  path_provider: ^2.0.15
  path_provider_ex2: ^2.0.12
  permission_handler: ^10.3.0
  on_audio_query: ^2.9.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  provider: ^6.0.5
  percent_indicator: ^4.2.3
  just_audio_background: ^0.0.1-beta.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/music_logo_light.png"

flutter_native_splash:
  image: assets/icons/music_logo_light.png
  color: "9C432E"
  android_disable_fullscreen: true